"""your change

Revision ID: 535a74706b71
Revises: 8df2949cf265
Create Date: 2026-04-17 20:15:09.946918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '535a74706b71'
down_revision: Union[str, Sequence[str], None] = '8df2949cf265'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('first_name', sa.String(length=255), nullable=False))
    op.add_column('clients', sa.Column('last_name', sa.String(length=255), nullable=False))
    op.alter_column('clients', 'phone',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
    op.drop_column('clients', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('full_name', mysql.VARCHAR(length=255), nullable=True))
    op.alter_column('clients', 'phone',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_column('clients', 'last_name')
    op.drop_column('clients', 'first_name')
    # ### end Alembic commands ###
