"""remove the imageurl from client and lawyer

Revision ID: 69a8ed0c404f
Revises: 535a74706b71
Create Date: 2026-04-17 20:38:19.354201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '69a8ed0c404f'
down_revision: Union[str, Sequence[str], None] = '535a74706b71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'image_url')
    op.drop_column('lawyers', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lawyers', sa.Column('image_url', mysql.VARCHAR(length=500), nullable=True))
    op.add_column('clients', sa.Column('image_url', mysql.VARCHAR(length=500), nullable=True))
    # ### end Alembic commands ###
